version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "news-ticker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lt8k1djuvy87"
s3_prefix = "news-ticker"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
